server:
  port: ${COMMUNICATION-SERVICE-PORT:3001}

spring:
  application:
    name: COMMUNICATION-SERVICE
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  config:
    import: classpath:db-config.yaml
  mail:


mail:
  from: ${MAIL_FROM:no-reply@example.com}
  host: ${MAIL_HOST}
  port: ${MAIL_PORT}
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}
  protocol: ${MAIL_PROTOCOL:smtp}
  properties:
    mail.smtp.auth: ${MAIL_SMTP_AUTH:true}
    mail.smtp.starttls.enable: ${MAIL_STARTTLS:true}

slack:
  enabled: ${SLACK_ENABLED:false}
  senderApp: ${SLACK_SENDER_APP:CoreMS}
  token: ${SLACK_BOT_TOKEN}
